repos:

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.9.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python Imports (src, tests)
        args: ["--application-directories", ".:src:tests"]

  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.6

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-encoding-pragma
      - id: debug-statements

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.5.0-1
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==19.10b0"]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]

  # Only enable this if the project will use Type Annotations
  # - repo: https://github.com/pre-commit/mirrors-mypy
    # rev: v0.761
    # hooks:
      # - id: mypy
