language: python

dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - pytest -ra

after_success:
  - coveralls

deploy:
  on:
    tags: true
    branch: master
  provider: pypi
  user: dougthor42
  password:
    secure: ""
  distributions: sdist bdist_wheel
