language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email: false

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .

script:
  - pytest -ra
