#
# Docker-compose file used when building and running locally (WSL)
#

# Need version >= 3.2 because of how we define our volumes
version: "3.2"
services:
  trendlines:
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - 5000:80
    volumes:
      # - type: bind
        # Host location. This can be anywhere on your file system.
        # source: c:/gitlab/github/trendlines/config
        # Within the container. The /data directory holds both the internal
        # database file (if you're using SQLite) and the configuration file
        # `trendlines.cfg`.
        # target: /data
      - type: bind
        source: c:/gitlab/github/trendlines/internal.db
        target: /data/internal.db
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "2003:2003"
    volumes:
      - type: bind
        # Host location. This can be anywhere on your file system.
        source: c:/gitlab/github/trendlines/config
        # Within the container. The /data directory holds both the internal
        # database file (if you're using SQLite) and the configuration file
        # `trendlines.cfg`.
        target: /data
    command: celery worker -l info -A trendlines.celery_app.celery
